name: x86-64 Pull and Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个英文逗号分开'
        required: true
        default: 'alpine:latest'


# GitHub Actions Node.js 24 兼容
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true


jobs:

  pull_and_package:

    runs-on: ubuntu-latest


    steps:

    - name: Checkout repository
      uses: actions/checkout@v5


    - name: Maximize Disk Space
      run: |
        echo "清理 GitHub Runner 空间..."

        sudo rm -rf /usr/share/dotnet || true
        sudo rm -rf /usr/local/lib/android || true
        sudo rm -rf /opt/ghc || true

        docker system prune -af

        df -h



    - name: Pull Docker Images and Package
      shell: bash
      run: |

        set -e


        images="${{ github.event.inputs.docker_images }}"

        # 删除空格
        images=$(echo "$images" | tr -d ' ')


        IFS=',' read -ra image_array <<< "$images"


        for image in "${image_array[@]}"
        do

          echo "=============================="
          echo "处理镜像:"
          echo "$image"
          echo "=============================="


          # 强制 amd64
          docker pull \
            --platform linux/amd64 \
            "$image"


          # 文件名安全转换
          safe_name=$(echo "$image" | sed 's#[/:]#_#g')


          docker save \
            "$image" \
            -o "${safe_name}-amd64.tar"


          echo "完成:"
          echo "${safe_name}-amd64.tar"


        done



    - name: Compress TAR files
      shell: bash
      run: |

        set -e


        files=$(ls *-amd64.tar 2>/dev/null || true)


        if [ -z "$files" ]; then
          echo "没有找到tar文件"
          exit 1
        fi


        echo "开始压缩:"
        echo "$files"


        tar -czf \
          x86-64-images-bundle.tar.gz \
          $files



        ls -lh *.tar.gz



    - name: Upload artifact
      uses: actions/upload-artifact@v5
      with:

        name: docker-offline-package

        path: x86-64-images-bundle.tar.gz

        retention-days: 3



    - name: Clean up
      if: always()
      run: |

        rm -f *.tar || true
        rm -f *.tar.gz || true
